#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef VISIONSDK_SWIFT_H
#define VISIONSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import Vision;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VisionSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


SWIFT_CLASS_NAMED("VSDKAnalyticsReportModel")
@interface VSDKAnalyticsReportModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("BOLReportModel")
@interface BOLReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM(NSInteger, CameraPosition, open) {
  CameraPositionBack = 1,
  CameraPositionFront = 2,
};

typedef SWIFT_ENUM(NSInteger, CaptureMode, open) {
  CaptureModeAuto = 0,
  CaptureModeManual = 1,
};

typedef SWIFT_ENUM(NSInteger, CaptureType, open) {
  CaptureTypeSingle = 0,
  CaptureTypeMultiple = 1,
};

typedef SWIFT_ENUM(NSInteger, CodeScannerError, open) {
  CodeScannerErrorCameraUsageNotAuthorized = 0,
  CodeScannerErrorNoTextDetected = 1,
  CodeScannerErrorNoBarCodeDetected = 2,
  CodeScannerErrorNoQRCodeDetected = 3,
  CodeScannerErrorNoBarCodeORQRCodeDetected = 4,
  CodeScannerErrorNoDocumentDetected = 5,
  CodeScannerErrorVideoUnavailable = 6,
  CodeScannerErrorAuthenticationNeededForPriceTagScanning = 7,
  CodeScannerErrorPriceTagDelegateNotImplemented = 8,
  CodeScannerErrorTemplateNotFound = 9,
  CodeScannerErrorNoTemplateCodesFound = 10,
  CodeScannerErrorItemRetrievalDelegateNotImplemented = 11,
  CodeScannerErrorAuthenticationNeededForItemRetrievalScanning = 12,
};

typedef SWIFT_ENUM(NSInteger, CodeScannerMode, open) {
  CodeScannerModeBarCode = 0,
  CodeScannerModeQrCode = 1,
  CodeScannerModeAutoBarCodeOrQRCode = 2,
  CodeScannerModeOcr = 3,
  CodeScannerModePhoto = 4,
  CodeScannerModePriceTag = 5,
  CodeScannerModeItemRetrieval = 6,
};

@class NSCoder;

SWIFT_CLASS_NAMED("CodeScannerView")
@interface CodeScannerView : UIView
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class UIColor;

SWIFT_CLASS_NAMED("FocusSettings")
@interface FocusSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) FocusSettings * _Nonnull default_;)
+ (FocusSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFocusImage:(UIImage * _Nullable)focusImage focusImageRect:(CGRect)focusImageRect shouldDisplayFocusImage:(BOOL)shouldDisplayFocusImage shouldScanInFocusImageRect:(BOOL)shouldScanInFocusImageRect showCodeBoundariesInMultipleScan:(BOOL)showCodeBoundariesInMultipleScan validCodeBoundryBorderColor:(UIColor * _Nonnull)validCodeBoundryBorderColor validCodeBoundryBorderWidth:(CGFloat)validCodeBoundryBorderWidth validCodeBoundryFillColor:(UIColor * _Nonnull)validCodeBoundryFillColor inValidCodeBoundryBorderColor:(UIColor * _Nonnull)inValidCodeBoundryBorderColor inValidCodeBoundryBorderWidth:(CGFloat)inValidCodeBoundryBorderWidth inValidCodeBoundryFillColor:(UIColor * _Nonnull)inValidCodeBoundryFillColor showDocumentBoundries:(BOOL)showDocumentBoundries documentBoundryBorderColor:(UIColor * _Nonnull)documentBoundryBorderColor documentBoundryBorderWidth:(CGFloat)documentBoundryBorderWidth documentBoundryFillColor:(UIColor * _Nonnull)documentBoundryFillColor focusImageTintColor:(UIColor * _Nonnull)focusImageTintColor focusImageHighlightedColor:(UIColor * _Nonnull)focusImageHighlightedColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;

SWIFT_CLASS_NAMED("ObjectDetectionConfiguration")
@interface ObjectDetectionConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) ObjectDetectionConfiguration * _Nonnull default_;)
+ (ObjectDetectionConfiguration * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithIsTextIndicationOn:(BOOL)isTextIndicationOn isBarCodeOrQRCodeIndicationOn:(BOOL)isBarCodeOrQRCodeIndicationOn isDocumentIndicationOn:(BOOL)isDocumentIndicationOn codeDetectionConfidence:(float)codeDetectionConfidence documentDetectionConfidence:(float)documentDetectionConfidence secondsToWaitBeforeDocumentCapture:(double)secondsToWaitBeforeDocumentCapture selectedTemplateId:(NSString * _Nullable)selectedTemplateId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CameraSettings")
@interface CameraSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) CameraSettings * _Nonnull default_;)
+ (CameraSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNthFrameToProcess:(int64_t)nthFrameToProcess cameraPosition:(enum CameraPosition)cameraPosition OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PriceTagDetectionSettings")
@interface PriceTagDetectionSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PriceTagDetectionSettings * _Nonnull default_;)
+ (PriceTagDetectionSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithShouldDisplayOnScreenIndicators:(BOOL)shouldDisplayOnScreenIndicators validTagImage:(UIImage * _Nonnull)validTagImage invalidTagImage:(UIImage * _Nonnull)invalidTagImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class AVCapturePhotoOutput;
@class AVCapturePhoto;
@class AVCaptureResolvedPhotoSettings;

@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK)) <AVCapturePhotoCaptureDelegate>
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhoto:(AVCapturePhoto * _Nonnull)photo error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output willCapturePhotoForResolvedSettings:(AVCaptureResolvedPhotoSettings * _Nonnull)resolvedSettings;
@end





@protocol CodeScannerViewDelegate;

@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK))
- (void)configureWithDelegate:(id <CodeScannerViewDelegate> _Nonnull)delegate sessionPreset:(AVCaptureSessionPreset _Nonnull)sessionPreset captureMode:(enum CaptureMode)captureMode captureType:(enum CaptureType)captureType scanMode:(enum CodeScannerMode)scanMode;
- (void)setScanModeTo:(enum CodeScannerMode)mode;
- (void)setCaptureModeTo:(enum CaptureMode)mode;
- (void)setCaptureTypeTo:(enum CaptureType)type;
- (void)setFocusSettingsTo:(FocusSettings * _Nonnull)focusSettings;
- (void)setObjectDetectionConfigurationTo:(ObjectDetectionConfiguration * _Nonnull)objectDetectionConfiguration;
- (void)setCameraSettingsTo:(CameraSettings * _Nonnull)cameraSettings;
- (void)setPriceTagDetectionSettingsTo:(PriceTagDetectionSettings * _Nonnull)priceTagDetectionSettings;
- (void)setSessionPresetTo:(AVCaptureSessionPreset _Nonnull)sessionPreset;
- (void)capturePhoto;
- (void)startRunning;
- (void)stopRunning;
- (void)rescan;
- (void)deConfigure;
+ (NSArray<NSString *> * _Nonnull)getAllTemplates SWIFT_WARN_UNUSED_RESULT;
+ (void)deleteTemplateWithId:(NSString * _Nonnull)id;
+ (void)deleteAllTemplates;
@end

@class NSError;
@class DetectedBarcode;

SWIFT_PROTOCOL_NAMED("CodeScannerViewDelegate")
@protocol CodeScannerViewDelegate
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didFailure:(NSError * _Nonnull)error;
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didSuccess:(NSArray<DetectedBarcode *> * _Nonnull)codes;
- (void)codeScannerViewDidDetect:(BOOL)text barCode:(BOOL)barCode qrCode:(BOOL)qrCode document:(BOOL)document;
@optional
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didCaptureOCRImage:(UIImage * _Nonnull)image withCroppedImge:(UIImage * _Nullable)croppedImage withbarCodes:(NSArray<NSString *> * _Nonnull)barcodes;
- (BOOL)codeScannerViewDidCapturePrice:(NSString * _Nonnull)price withSKU:(NSString * _Nonnull)sKU SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSNumber *> * _Nonnull)codeScannerViewDidCaptureItemCodesWith:(NSArray<NSString *> * _Nonnull)codes SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DCReportModel")
@interface DCReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DetectedBarcode")
@interface DetectedBarcode : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stringValue;
@property (nonatomic, readonly) VNBarcodeSymbology _Nonnull symbology;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable extractedData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class NSBundle;

SWIFT_CLASS_NAMED("GenerateTemplateController")
@interface GenerateTemplateController : UIViewController
+ (GenerateTemplateController * _Nonnull)instantiate SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface GenerateTemplateController (SWIFT_EXTENSION(VisionSDK)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end


@interface GenerateTemplateController (SWIFT_EXTENSION(VisionSDK))
- (void)startRunning;
- (void)stopRunning;
@end


SWIFT_PROTOCOL_NAMED("GenerateTemplateControllerDelegate")
@protocol GenerateTemplateControllerDelegate
- (void)templateScanController:(GenerateTemplateController * _Nonnull)controller didFinishWith:(NSString * _Nonnull)result;
- (void)templateScanController:(GenerateTemplateController * _Nonnull)controller didFailWithError:(NSError * _Nonnull)error;
- (void)templateScanControllerDidCancel:(GenerateTemplateController * _Nonnull)controller;
@end


SWIFT_CLASS_NAMED("ILReportModel")
@interface ILReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





typedef SWIFT_ENUM(NSInteger, OCRMode, open) {
  OCRModeOnline = 0,
  OCRModeOffline = 1,
};

@class NSURL;
enum VSDKModelExternalClass : NSInteger;
enum VSDKModelExternalSize : NSInteger;
@class CIImage;
@class NSData;

SWIFT_CLASS_NAMED("OnDeviceOCRManager")
@interface OnDeviceOCRManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OnDeviceOCRManager * _Nonnull shared;)
+ (OnDeviceOCRManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSURL * _Nullable)getVSDKLogs SWIFT_WARN_UNUSED_RESULT;
- (void)reportErrorWith:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize image:(CIImage * _Nullable)image reportText:(NSString * _Nonnull)reportText response:(NSData * _Nullable)response reportModel:(VSDKAnalyticsReportModel * _Nullable)reportModel withCompletion:(void (^ _Nullable)(NSInteger))completion;
- (void)prepareOfflineOCRWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withProgressTracking:(void (^ _Nullable)(float, float, BOOL))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)prepareOfflineOCRWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withProgressTracking:(void (^ _Nullable)(float, float, BOOL))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)extractDataFromImage:(CIImage * _Nonnull)image withBarcodes:(NSArray<NSString *> * _Nonnull)barcodes :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end






SWIFT_CLASS_NAMED("SLReportModel")
@interface SLReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






typedef SWIFT_ENUM(NSInteger, VSDKAppEnvironment, open) {
  VSDKAppEnvironmentDev = 0,
  VSDKAppEnvironmentQa = 1,
  VSDKAppEnvironmentStaging = 2,
  VSDKAppEnvironmentProduction = 3,
  VSDKAppEnvironmentSandbox = 4,
};


SWIFT_CLASS_NAMED("VSDKConstants")
@interface Constants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VSDKModelExternalClass, open) {
  VSDKModelExternalClassShippingLabel = 0,
  VSDKModelExternalClassBillOfLading = 1,
  VSDKModelExternalClassItemLabel = 2,
  VSDKModelExternalClassDocumentClassification = 3,
};

typedef SWIFT_ENUM(NSInteger, VSDKModelExternalSize, open) {
  VSDKModelExternalSizeNano = 0,
  VSDKModelExternalSizeMicro = 1,
  VSDKModelExternalSizeSmall = 2,
  VSDKModelExternalSizeMedium = 3,
  VSDKModelExternalSizeLarge = 4,
  VSDKModelExternalSizeXlarge = 5,
};


SWIFT_CLASS_NAMED("VisionAPIManager")
@interface VisionAPIManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VisionAPIManager * _Nonnull shared;)
+ (VisionAPIManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface VisionAPIManager (SWIFT_EXTENSION(VisionSDK))
- (void)checkScanningFeatureAuthenticationWithKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)callScanAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData andRecipient:(NSDictionary<NSString *, id> * _Nullable)recipient andSender:(NSDictionary<NSString *, id> * _Nullable)sender withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)getPredictionBillOfLadingCloud:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callDocumentClassificationAPIWith:(UIImage * _Nonnull)image andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callItemLabelsAPIWith:(UIImage * _Nonnull)image andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callMatchingAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withResponseData:(NSData * _Nonnull)responseData andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData andRecipient:(NSDictionary<NSString *, id> * _Nullable)recipient andSender:(NSDictionary<NSString *, id> * _Nullable)sender withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef VISIONSDK_SWIFT_H
#define VISIONSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import Vision;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VisionSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


SWIFT_CLASS_NAMED("VSDKAnalyticsReportModel")
@interface VSDKAnalyticsReportModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("BOLReportModel")
@interface BOLReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM(NSInteger, CameraPosition, open) {
  CameraPositionBack = 1,
  CameraPositionFront = 2,
};

typedef SWIFT_ENUM(NSInteger, CaptureMode, open) {
  CaptureModeAuto = 0,
  CaptureModeManual = 1,
};

typedef SWIFT_ENUM(NSInteger, CaptureType, open) {
  CaptureTypeSingle = 0,
  CaptureTypeMultiple = 1,
};

typedef SWIFT_ENUM(NSInteger, CodeScannerError, open) {
  CodeScannerErrorCameraUsageNotAuthorized = 0,
  CodeScannerErrorNoTextDetected = 1,
  CodeScannerErrorNoBarCodeDetected = 2,
  CodeScannerErrorNoQRCodeDetected = 3,
  CodeScannerErrorNoBarCodeORQRCodeDetected = 4,
  CodeScannerErrorNoDocumentDetected = 5,
  CodeScannerErrorVideoUnavailable = 6,
  CodeScannerErrorAuthenticationNeededForPriceTagScanning = 7,
  CodeScannerErrorPriceTagDelegateNotImplemented = 8,
  CodeScannerErrorTemplateNotFound = 9,
  CodeScannerErrorNoTemplateCodesFound = 10,
  CodeScannerErrorItemRetrievalDelegateNotImplemented = 11,
  CodeScannerErrorAuthenticationNeededForItemRetrievalScanning = 12,
};

typedef SWIFT_ENUM(NSInteger, CodeScannerMode, open) {
  CodeScannerModeBarCode = 0,
  CodeScannerModeQrCode = 1,
  CodeScannerModeAutoBarCodeOrQRCode = 2,
  CodeScannerModeOcr = 3,
  CodeScannerModePhoto = 4,
  CodeScannerModePriceTag = 5,
  CodeScannerModeItemRetrieval = 6,
};

@class NSCoder;

SWIFT_CLASS_NAMED("CodeScannerView")
@interface CodeScannerView : UIView
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class UIColor;

SWIFT_CLASS_NAMED("FocusSettings")
@interface FocusSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) FocusSettings * _Nonnull default_;)
+ (FocusSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFocusImage:(UIImage * _Nullable)focusImage focusImageRect:(CGRect)focusImageRect shouldDisplayFocusImage:(BOOL)shouldDisplayFocusImage shouldScanInFocusImageRect:(BOOL)shouldScanInFocusImageRect showCodeBoundariesInMultipleScan:(BOOL)showCodeBoundariesInMultipleScan validCodeBoundryBorderColor:(UIColor * _Nonnull)validCodeBoundryBorderColor validCodeBoundryBorderWidth:(CGFloat)validCodeBoundryBorderWidth validCodeBoundryFillColor:(UIColor * _Nonnull)validCodeBoundryFillColor inValidCodeBoundryBorderColor:(UIColor * _Nonnull)inValidCodeBoundryBorderColor inValidCodeBoundryBorderWidth:(CGFloat)inValidCodeBoundryBorderWidth inValidCodeBoundryFillColor:(UIColor * _Nonnull)inValidCodeBoundryFillColor showDocumentBoundries:(BOOL)showDocumentBoundries documentBoundryBorderColor:(UIColor * _Nonnull)documentBoundryBorderColor documentBoundryBorderWidth:(CGFloat)documentBoundryBorderWidth documentBoundryFillColor:(UIColor * _Nonnull)documentBoundryFillColor focusImageTintColor:(UIColor * _Nonnull)focusImageTintColor focusImageHighlightedColor:(UIColor * _Nonnull)focusImageHighlightedColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;

SWIFT_CLASS_NAMED("ObjectDetectionConfiguration")
@interface ObjectDetectionConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) ObjectDetectionConfiguration * _Nonnull default_;)
+ (ObjectDetectionConfiguration * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithIsTextIndicationOn:(BOOL)isTextIndicationOn isBarCodeOrQRCodeIndicationOn:(BOOL)isBarCodeOrQRCodeIndicationOn isDocumentIndicationOn:(BOOL)isDocumentIndicationOn codeDetectionConfidence:(float)codeDetectionConfidence documentDetectionConfidence:(float)documentDetectionConfidence secondsToWaitBeforeDocumentCapture:(double)secondsToWaitBeforeDocumentCapture selectedTemplateId:(NSString * _Nullable)selectedTemplateId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CameraSettings")
@interface CameraSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) CameraSettings * _Nonnull default_;)
+ (CameraSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNthFrameToProcess:(int64_t)nthFrameToProcess cameraPosition:(enum CameraPosition)cameraPosition OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PriceTagDetectionSettings")
@interface PriceTagDetectionSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PriceTagDetectionSettings * _Nonnull default_;)
+ (PriceTagDetectionSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithShouldDisplayOnScreenIndicators:(BOOL)shouldDisplayOnScreenIndicators validTagImage:(UIImage * _Nonnull)validTagImage invalidTagImage:(UIImage * _Nonnull)invalidTagImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class AVCapturePhotoOutput;
@class AVCapturePhoto;
@class AVCaptureResolvedPhotoSettings;

@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK)) <AVCapturePhotoCaptureDelegate>
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhoto:(AVCapturePhoto * _Nonnull)photo error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output willCapturePhotoForResolvedSettings:(AVCaptureResolvedPhotoSettings * _Nonnull)resolvedSettings;
@end





@protocol CodeScannerViewDelegate;

@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK))
- (void)configureWithDelegate:(id <CodeScannerViewDelegate> _Nonnull)delegate sessionPreset:(AVCaptureSessionPreset _Nonnull)sessionPreset captureMode:(enum CaptureMode)captureMode captureType:(enum CaptureType)captureType scanMode:(enum CodeScannerMode)scanMode;
- (void)setScanModeTo:(enum CodeScannerMode)mode;
- (void)setCaptureModeTo:(enum CaptureMode)mode;
- (void)setCaptureTypeTo:(enum CaptureType)type;
- (void)setFocusSettingsTo:(FocusSettings * _Nonnull)focusSettings;
- (void)setObjectDetectionConfigurationTo:(ObjectDetectionConfiguration * _Nonnull)objectDetectionConfiguration;
- (void)setCameraSettingsTo:(CameraSettings * _Nonnull)cameraSettings;
- (void)setPriceTagDetectionSettingsTo:(PriceTagDetectionSettings * _Nonnull)priceTagDetectionSettings;
- (void)setSessionPresetTo:(AVCaptureSessionPreset _Nonnull)sessionPreset;
- (void)capturePhoto;
- (void)startRunning;
- (void)stopRunning;
- (void)rescan;
- (void)deConfigure;
+ (NSArray<NSString *> * _Nonnull)getAllTemplates SWIFT_WARN_UNUSED_RESULT;
+ (void)deleteTemplateWithId:(NSString * _Nonnull)id;
+ (void)deleteAllTemplates;
@end

@class NSError;
@class DetectedBarcode;

SWIFT_PROTOCOL_NAMED("CodeScannerViewDelegate")
@protocol CodeScannerViewDelegate
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didFailure:(NSError * _Nonnull)error;
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didSuccess:(NSArray<DetectedBarcode *> * _Nonnull)codes;
- (void)codeScannerViewDidDetect:(BOOL)text barCode:(BOOL)barCode qrCode:(BOOL)qrCode document:(BOOL)document;
@optional
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didCaptureOCRImage:(UIImage * _Nonnull)image withCroppedImge:(UIImage * _Nullable)croppedImage withbarCodes:(NSArray<NSString *> * _Nonnull)barcodes;
- (BOOL)codeScannerViewDidCapturePrice:(NSString * _Nonnull)price withSKU:(NSString * _Nonnull)sKU SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSNumber *> * _Nonnull)codeScannerViewDidCaptureItemCodesWith:(NSArray<NSString *> * _Nonnull)codes SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("DCReportModel")
@interface DCReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("DetectedBarcode")
@interface DetectedBarcode : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stringValue;
@property (nonatomic, readonly) VNBarcodeSymbology _Nonnull symbology;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable extractedData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class NSBundle;

SWIFT_CLASS_NAMED("GenerateTemplateController")
@interface GenerateTemplateController : UIViewController
+ (GenerateTemplateController * _Nonnull)instantiate SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface GenerateTemplateController (SWIFT_EXTENSION(VisionSDK)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end


@interface GenerateTemplateController (SWIFT_EXTENSION(VisionSDK))
- (void)startRunning;
- (void)stopRunning;
@end


SWIFT_PROTOCOL_NAMED("GenerateTemplateControllerDelegate")
@protocol GenerateTemplateControllerDelegate
- (void)templateScanController:(GenerateTemplateController * _Nonnull)controller didFinishWith:(NSString * _Nonnull)result;
- (void)templateScanController:(GenerateTemplateController * _Nonnull)controller didFailWithError:(NSError * _Nonnull)error;
- (void)templateScanControllerDidCancel:(GenerateTemplateController * _Nonnull)controller;
@end


SWIFT_CLASS_NAMED("ILReportModel")
@interface ILReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





typedef SWIFT_ENUM(NSInteger, OCRMode, open) {
  OCRModeOnline = 0,
  OCRModeOffline = 1,
};

@class NSURL;
enum VSDKModelExternalClass : NSInteger;
enum VSDKModelExternalSize : NSInteger;
@class CIImage;
@class NSData;

SWIFT_CLASS_NAMED("OnDeviceOCRManager")
@interface OnDeviceOCRManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OnDeviceOCRManager * _Nonnull shared;)
+ (OnDeviceOCRManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSURL * _Nullable)getVSDKLogs SWIFT_WARN_UNUSED_RESULT;
- (void)reportErrorWith:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize image:(CIImage * _Nullable)image reportText:(NSString * _Nonnull)reportText response:(NSData * _Nullable)response reportModel:(VSDKAnalyticsReportModel * _Nullable)reportModel withCompletion:(void (^ _Nullable)(NSInteger))completion;
- (void)prepareOfflineOCRWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withProgressTracking:(void (^ _Nullable)(float, float, BOOL))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)prepareOfflineOCRWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withProgressTracking:(void (^ _Nullable)(float, float, BOOL))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)extractDataFromImage:(CIImage * _Nonnull)image withBarcodes:(NSArray<NSString *> * _Nonnull)barcodes :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end






SWIFT_CLASS_NAMED("SLReportModel")
@interface SLReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






typedef SWIFT_ENUM(NSInteger, VSDKAppEnvironment, open) {
  VSDKAppEnvironmentDev = 0,
  VSDKAppEnvironmentQa = 1,
  VSDKAppEnvironmentStaging = 2,
  VSDKAppEnvironmentProduction = 3,
  VSDKAppEnvironmentSandbox = 4,
};


SWIFT_CLASS_NAMED("VSDKConstants")
@interface Constants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VSDKModelExternalClass, open) {
  VSDKModelExternalClassShippingLabel = 0,
  VSDKModelExternalClassBillOfLading = 1,
  VSDKModelExternalClassItemLabel = 2,
  VSDKModelExternalClassDocumentClassification = 3,
};

typedef SWIFT_ENUM(NSInteger, VSDKModelExternalSize, open) {
  VSDKModelExternalSizeNano = 0,
  VSDKModelExternalSizeMicro = 1,
  VSDKModelExternalSizeSmall = 2,
  VSDKModelExternalSizeMedium = 3,
  VSDKModelExternalSizeLarge = 4,
  VSDKModelExternalSizeXlarge = 5,
};


SWIFT_CLASS_NAMED("VisionAPIManager")
@interface VisionAPIManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VisionAPIManager * _Nonnull shared;)
+ (VisionAPIManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface VisionAPIManager (SWIFT_EXTENSION(VisionSDK))
- (void)checkScanningFeatureAuthenticationWithKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)callScanAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData andRecipient:(NSDictionary<NSString *, id> * _Nullable)recipient andSender:(NSDictionary<NSString *, id> * _Nullable)sender withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)getPredictionBillOfLadingCloud:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callDocumentClassificationAPIWith:(UIImage * _Nonnull)image andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callItemLabelsAPIWith:(UIImage * _Nonnull)image andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callMatchingAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withResponseData:(NSData * _Nonnull)responseData andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData andRecipient:(NSDictionary<NSString *, id> * _Nullable)recipient andSender:(NSDictionary<NSString *, id> * _Nullable)sender withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
