#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef VISIONSDK_SWIFT_H
#define VISIONSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VisionSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VisionSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("VSDKAnalyticsReportModel")
@interface VSDKAnalyticsReportModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("BOLReportModel")
@interface BOLReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, BarcodeSymbology, open) {
  BarcodeSymbologyAztec = 0,
  BarcodeSymbologyCodabar = 1,
  BarcodeSymbologyCode128 = 2,
  BarcodeSymbologyCode39 = 3,
  BarcodeSymbologyCode39Checksum = 4,
  BarcodeSymbologyCode39FullASCII = 5,
  BarcodeSymbologyCode39FullASCIIChecksum = 6,
  BarcodeSymbologyCode93 = 7,
  BarcodeSymbologyCode93i = 8,
  BarcodeSymbologyDataMatrix = 9,
  BarcodeSymbologyEan13 = 10,
  BarcodeSymbologyEan8 = 11,
  BarcodeSymbologyGs1DataBar = 12,
  BarcodeSymbologyGs1DataBarExpanded = 13,
  BarcodeSymbologyGs1DataBarLimited = 14,
  BarcodeSymbologyI2of5 = 15,
  BarcodeSymbologyI2of5Checksum = 16,
  BarcodeSymbologyItf14 = 17,
  BarcodeSymbologyMsiPlessey = 18,
  BarcodeSymbologyMicroPDF417 = 19,
  BarcodeSymbologyMicroQR = 20,
  BarcodeSymbologyPdf417 = 21,
  BarcodeSymbologyQr = 22,
  BarcodeSymbologyUpce = 23,
  BarcodeSymbologyUnknown = 24,
  BarcodeSymbologyUpca = 25,
};

typedef SWIFT_ENUM(NSInteger, CameraLiveGuidance, open) {
  CameraLiveGuidanceMoveCloser = 0,
  CameraLiveGuidanceMoveBack = 1,
  CameraLiveGuidanceHoldStill = 2,
  CameraLiveGuidancePointCameraToDocument = 3,
};

typedef SWIFT_ENUM(NSInteger, CameraPosition, open) {
  CameraPositionBack = 1,
  CameraPositionFront = 2,
};

typedef SWIFT_ENUM(NSInteger, CaptureMode, open) {
  CaptureModeAuto = 0,
  CaptureModeManual = 1,
};

typedef SWIFT_ENUM(NSInteger, CaptureType, open) {
  CaptureTypeSingle = 0,
  CaptureTypeMultiple = 1,
};

typedef SWIFT_ENUM(NSInteger, CodeScannerError, open) {
  CodeScannerErrorCameraUsageNotAuthorized = 0,
  CodeScannerErrorNoTextDetected = 1,
  CodeScannerErrorNoBarCodeDetected = 2,
  CodeScannerErrorNoQRCodeDetected = 3,
  CodeScannerErrorNoBarCodeORQRCodeDetected = 4,
  CodeScannerErrorNoDocumentDetected = 5,
  CodeScannerErrorVideoUnavailable = 6,
  CodeScannerErrorAuthenticationNeededForPriceTagScanning = 7,
  CodeScannerErrorPriceTagDelegateNotImplemented = 8,
  CodeScannerErrorTemplateNotFound = 9,
  CodeScannerErrorNoTemplateCodesFound = 10,
  CodeScannerErrorItemRetrievalDelegateNotImplemented = 11,
  CodeScannerErrorAuthenticationNeededForItemRetrievalScanning = 12,
};

typedef SWIFT_ENUM(NSInteger, CodeScannerMode, open) {
  CodeScannerModeBarCode = 0,
  CodeScannerModeQrCode = 1,
  CodeScannerModeAutoBarCodeOrQRCode = 2,
  CodeScannerModeOcr = 3,
  CodeScannerModePhoto = 4,
  CodeScannerModePriceTag = 5,
  CodeScannerModeItemRetrieval = 6,
};

@class VSDKCameraState;
SWIFT_ENUM_FWD_DECL(NSInteger, VSDKFocusMode)
@class VSDKLensSelection;
@class NSCoder;
SWIFT_CLASS_NAMED("CodeScannerView")
@interface CodeScannerView : UIView
/// Android parity: <code>VisionCameraView.setZoomRatio(zoomRatio: Float)</code>. Routes straight through
/// to <code>VSDKCameraController.setZoom(_:)</code>, which stores the RAW desired ratio in
/// <code>RuntimeSettingsStore</code> (clamped only at apply-time, never here) and applies it to the live
/// device if already <code>.running</code>. This is what fixes the I-4 regression: the RN iOS bridge used
/// to write <code>videoDevice.videoZoomFactor</code> directly, which <code>SessionReconciler</code> clobbered back to
/// its bind-time default on every rebind (e.g. background -> foreground) – going through the
/// controller instead means <code>SessionReconciler.applyDesiredRuntimeSettingsToLiveDevice</code>
/// re-applies this exact desired value on every subsequent bind, so it survives.
/// Calling this BEFORE <code>configure(...)</code> still lands on the first bind: <code>cameraSession</code> is a
/// <code>private lazy var</code>, so this call is enough to construct it (same lazy-construction path
/// <code>configure()</code> itself relies on) and its freshly-created <code>RuntimeSettingsStore</code> already holds
/// this value by the time <code>start(with:)</code> binds for the first time – no separate
/// pending-value plumbing needed.
- (void)setZoomRatio:(float)ratio;
/// Android parity: <code>VisionCameraView.setLinearZoom(zoomLevel: Float)</code>. Routes to
/// <code>VSDKCameraController.setLinearZoom(_:)</code>, which stores the RAW desired 0…1 linear value
/// (clearing the ratio-mode sentinel, mirroring Android’s mutual exclusion) and defers the
/// linear->ratio conversion to apply-time against whatever range is live then. Same
/// pre-configure and rebind-persistence behavior as <code>setZoomRatio(_:)</code> above.
- (void)setLinearZoom:(float)zoomLevel;
/// Android parity: <code>VisionCameraView.setFlashTurnedOn(enabled: Bool)</code>. Routes to
/// <code>VSDKCameraController.setTorchEnabled(_:)</code>, same persistence discipline as the zoom setters
/// above (desired value stored in <code>RuntimeSettingsStore</code>, re-applied on every bind).
- (void)setFlashTurnedOn:(BOOL)enabled;
/// Android parity: <code>VisionCameraView.getCurrentZoomRatio(): Float?</code>. Reads the session’s
/// current LIVE state (not the desired-but-not-yet-applied value) – <code>1.0</code> pre-bind/idle,
/// matching <code>VSDKCameraState.idle(facing:)</code>’s nominal default.
- (float)getCurrentZoomRatio SWIFT_WARN_UNUSED_RESULT;
/// Android parity: <code>VisionCameraView.getMinZoomRatioAvailable(): Float?</code>. Live wide-normalized
/// lower bound – <code>1.0</code> pre-bind/idle, matching <code>VSDKCameraState.idle(facing:)</code>‘s nominal
/// default. Android returns <code>Float?</code> (null pre-bind); <code>@objc</code> can’t cleanly return <code>Float?</code>,
/// so this stays non-optional – the RN bridge normalizes this nullability difference.
- (float)getMinZoomRatioAvailable SWIFT_WARN_UNUSED_RESULT;
/// Android parity: <code>VisionCameraView.getMaxZoomRatioAvailable(): Float?</code>. Live wide-normalized
/// upper bound – <code>1.0</code> pre-bind/idle, matching <code>VSDKCameraState.idle(facing:)</code>’s nominal
/// default. Same non-optional-vs-<code>Float?</code> acceptance as <code>getMinZoomRatioAvailable()</code> above.
- (float)getMaxZoomRatioAvailable SWIFT_WARN_UNUSED_RESULT;
/// Android parity: <code>VisionCameraView.currentLinearZoom(): Float?</code>. Routes to
/// <code>VSDKCameraController.currentLinearZoom()</code>, which reads back the live <code>zoomRatio</code> as a
/// 0…1 FOV-linear value via <code>ZoomConversion.linearZoomForRatio</code> – <code>0</code> pre-bind/idle
/// (degenerate 1.0…1.0 range), regardless of whether <code>setZoom</code>/<code>setLinearZoom</code> last drove
/// the ratio there. Same non-optional-vs-<code>Float?</code> acceptance as the two getters above.
- (float)currentLinearZoom SWIFT_WARN_UNUSED_RESULT;
/// Replay-on-attach accessor for the current camera state snapshot – mirrors
/// <code>VSDKCameraSession.currentState</code>. Lets a newly-attached RN state listener read the live
/// state immediately instead of waiting for the next <code>didChangeCameraState</code> delegate callback.
@property (nonatomic, readonly, strong) VSDKCameraState * _Nonnull currentCameraState;
/// Routes to <code>VSDKCameraController.setFocusPoint(_:)</code> – one-shot autofocus/metering at a
/// VIEW-normalized (0…1, {0,0} top-left / {1,1} bottom-right of this view’s bounds) point.
/// Unrelated to <code>setFocusSettings</code>, which configures overlay styling, not runtime autofocus
/// behavior.
/// Cross-platform contract: Android’s <code>VisionCameraView</code>/the RN prop both take a
/// VIEW-normalized 0…1 point, not device-space – so this method converts internally
/// instead of forwarding the raw value, exactly like the SDK’s own tap-to-focus
/// (<code>CodeScannerView+Gestures.swift:57-62</code>, <code>handleTapToFocus(atLayerPoint:)</code>): view-normalized
/// -> layer point (the preview layer fills <code>self.bounds</code>, see addPreviewLayer()/
/// adjustPreviewLayer() below) -> <code>captureDevicePointConverted(fromLayerPoint:)</code> -> device
/// space. <code>x</code>/<code>y</code> are clamped to 0…1 first so an out-of-range caller can’t hand
/// <code>focusPointOfInterest</code> a point outside its documented domain.
- (void)setFocusPoint:(CGPoint)point;
/// Routes to <code>VSDKCameraController.setFocusMode(_:)</code>.
- (void)setFocusMode:(enum VSDKFocusMode)mode;
/// Applies an already-resolved lens selection (auto or pinned) to the live session. JS
/// id -> <code>VSDKLens</code> resolution against <code>VSDKCameraCapabilities</code> happens in the RN Swift
/// bridge, not here – this method only accepts a resolved <code>VSDKLensSelection</code>.
/// Stores <code>selection</code> into <code>lensSelection</code> (not just a one-off local <code>config</code>) so every
/// LATER view-driven config rebuild – stop/start, <code>setSessionPresetTo</code>, pre-bind –
/// continues to include this pin via <code>makeCameraConfiguration()</code> instead of dropping it
/// back to <code>.automatic</code>.
- (void)setLensSelection:(VSDKLensSelection * _Nonnull)selection;
/// Android parity: <code>VisionCameraView.enableTapToFocus()</code>. Flips the gate the
/// <code>UITapGestureRecognizer</code> handler (see CodeScannerView+Gestures.swift) checks on every
/// tap; the recognizer itself is always attached (see <code>setupGestureRecognizersIfNeeded()</code>,
/// called from <code>configure(...)</code>), mirroring Android’s always-present detector that only
/// acts when its own flag is on. Default is <code>false</code>, matching Android.
- (void)enableTapToFocus;
/// Android parity: <code>VisionCameraView.disableTapToFocus()</code>.
- (void)disableTapToFocus;
/// Android parity: <code>VisionCameraView.enablePinchPanToZoom()</code>. Same always-attached/
/// flag-gated shape as <code>enableTapToFocus()</code> above, for the <code>UIPinchGestureRecognizer</code>.
- (void)enablePinchPanToZoom;
/// Android parity: <code>VisionCameraView.disablePinchPanToZoom()</code>.
- (void)disablePinchPanToZoom;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class UIColor;
SWIFT_CLASS_NAMED("FocusSettings")
@interface FocusSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) FocusSettings * _Nonnull default_;)
+ (FocusSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFocusImage:(UIImage * _Nullable)focusImage focusImageRect:(CGRect)focusImageRect shouldDisplayFocusImage:(BOOL)shouldDisplayFocusImage shouldScanInFocusImageRect:(BOOL)shouldScanInFocusImageRect showCodeBoundariesInMultipleScan:(BOOL)showCodeBoundariesInMultipleScan validCodeBoundryBorderColor:(UIColor * _Nonnull)validCodeBoundryBorderColor validCodeBoundryBorderWidth:(CGFloat)validCodeBoundryBorderWidth validCodeBoundryFillColor:(UIColor * _Nonnull)validCodeBoundryFillColor inValidCodeBoundryBorderColor:(UIColor * _Nonnull)inValidCodeBoundryBorderColor inValidCodeBoundryBorderWidth:(CGFloat)inValidCodeBoundryBorderWidth inValidCodeBoundryFillColor:(UIColor * _Nonnull)inValidCodeBoundryFillColor showDocumentBoundries:(BOOL)showDocumentBoundries documentBoundryBorderColor:(UIColor * _Nonnull)documentBoundryBorderColor documentBoundryBorderWidth:(CGFloat)documentBoundryBorderWidth documentBoundryFillColor:(UIColor * _Nonnull)documentBoundryFillColor focusImageTintColor:(UIColor * _Nonnull)focusImageTintColor focusImageHighlightedColor:(UIColor * _Nonnull)focusImageHighlightedColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;
SWIFT_CLASS_NAMED("ObjectDetectionConfiguration")
@interface ObjectDetectionConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) ObjectDetectionConfiguration * _Nonnull default_;)
+ (ObjectDetectionConfiguration * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithIsTextIndicationOn:(BOOL)isTextIndicationOn isBarCodeOrQRCodeIndicationOn:(BOOL)isBarCodeOrQRCodeIndicationOn isDocumentIndicationOn:(BOOL)isDocumentIndicationOn codeDetectionConfidence:(float)codeDetectionConfidence documentDetectionConfidence:(float)documentDetectionConfidence secondsToWaitBeforeDocumentCapture:(double)secondsToWaitBeforeDocumentCapture selectedTemplate:(NSData * _Nullable)selectedTemplate OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CameraSettings")
@interface CameraSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) CameraSettings * _Nonnull default_;)
+ (CameraSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNthFrameToProcess:(int64_t)nthFrameToProcess cameraPosition:(enum CameraPosition)cameraPosition OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("PriceTagDetectionSettings")
@interface PriceTagDetectionSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) PriceTagDetectionSettings * _Nonnull default_;)
+ (PriceTagDetectionSettings * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithShouldDisplayOnScreenIndicators:(BOOL)shouldDisplayOnScreenIndicators validTagImage:(UIImage * _Nullable)validTagImage invalidTagImage:(UIImage * _Nullable)invalidTagImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureOutput;
@class AVCaptureConnection;
@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK)) <AVCaptureVideoDataOutputSampleBufferDelegate>
/// Kept per Resolved ambiguity #4 – dead-in-practice post-swap, since nothing sets <code>self</code>
/// as any AVCaptureVideoDataOutput’s sample buffer delegate anymore (VSDKCameraSession’s own
/// FrameDispatcher owns that role now). Refactored to funnel through the same onFrame(_:)
/// every real frame now goes through, rather than duplicating its dispatch logic.
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class AVCapturePhotoOutput;
@class AVCapturePhoto;
@class AVCaptureResolvedPhotoSettings;
@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK)) <AVCapturePhotoCaptureDelegate>
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhoto:(AVCapturePhoto * _Nonnull)photo error:(NSError * _Nullable)error;
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output willCapturePhotoForResolvedSettings:(AVCaptureResolvedPhotoSettings * _Nonnull)resolvedSettings;
@end

@protocol CodeScannerViewDelegate;
@class AVCapturePhotoSettings;
@interface CodeScannerView (SWIFT_EXTENSION(VisionSDK))
- (void)configureWithDelegate:(id <CodeScannerViewDelegate> _Nonnull)delegate sessionPreset:(AVCaptureSessionPreset _Nonnull)sessionPreset captureMode:(enum CaptureMode)captureMode captureType:(enum CaptureType)captureType scanMode:(enum CodeScannerMode)scanMode isLongDistanceScanningEnabled:(BOOL)isLongDistanceScanningEnabled;
- (void)setScanModeTo:(enum CodeScannerMode)mode;
- (void)setCaptureModeTo:(enum CaptureMode)mode;
- (void)setCaptureTypeTo:(enum CaptureType)type;
- (void)setFocusSettingsTo:(FocusSettings * _Nonnull)focusSettings;
- (void)setObjectDetectionConfigurationTo:(ObjectDetectionConfiguration * _Nonnull)objectDetectionConfiguration;
- (void)setCameraSettingsTo:(CameraSettings * _Nonnull)cameraSettings;
- (void)setPriceTagDetectionSettingsTo:(PriceTagDetectionSettings * _Nonnull)priceTagDetectionSettings;
- (void)setSessionPresetTo:(AVCaptureSessionPreset _Nonnull)sessionPreset;
- (void)capturePhoto;
- (void)capturePhotoUsingPhotoSettings:(AVCapturePhotoSettings * _Nonnull)photoSettings;
- (void)startRunning;
/// Non-blocking by design: VSDKCameraSession.stop() hops onto its own session queue and
/// returns immediately – a synchronous wait here would risk a main-thread deadlock against
/// the state observer’s main-queue delivery (Phase 2 plan, Resolved ambiguity #1; Task 0’s
/// hardware spike proved the deadlock risk on-device). Callers that need to observe the
/// session actually reaching IDLE must do so via VSDKCameraStateObserver, not by assuming
/// this call has finished by the time it returns.
- (void)stopRunning;
/// C1/Resolved ambiguity #5: rescan() NEVER stops-then-starts – it never did. Today’s
/// <code>guard !session.isRunning else { return }</code> IS the no-stop invariant, just phrased as an
/// early return instead of an explicit call; this reproduces the same net effect by calling
/// the no-arg cameraSession.start() UNCONDITIONALLY (never cameraSession.stop()) – a no-op
/// on an already-.running session (SessionReconciler.start()’s .starting/.running/.interrupted
/// branches are all no-ops). RN’s every-scan call pattern depends on this.
- (void)rescan;
- (void)deConfigure;
/// Pauses all per-frame detection work while keeping the capture session and
/// preview alive — for moments like “photo captured, showing a loading
/// spinner” where a full stop/restart of the session would be wasteful and
/// visually jarring. Reconciles with captureOutput’s existing frame-skip guard
/// via <code>isAnalysisPaused</code> rather than adding a second, overlapping bail-out
/// path. Does not reach VisionSDKDimensioning — that module has its own
/// VSDKDimensioningSession.pause()/.resume(). Overlay-clearing is added in a
/// later change (see clearDetectionOverlays()).
- (void)pauseDetection;
/// Resumes per-frame detection work previously paused via pauseDetection().
- (void)resumeDetection;
@end

@class NSError;
@class DetectedCode;
@class NSString;
SWIFT_PROTOCOL_NAMED("CodeScannerViewDelegate")
@protocol CodeScannerViewDelegate
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didFailure:(NSError * _Nonnull)error;
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didSuccess:(NSArray<DetectedCode *> * _Nonnull)codes;
@optional
- (void)codeScannerViewDidDetectBoxes:(BOOL)text barCode:(NSArray<DetectedCode *> * _Nonnull)barCode qrCode:(NSArray<DetectedCode *> * _Nonnull)qrCode document:(CGRect)document;
@required
- (void)codeScannerViewDidDetect:(BOOL)text barCode:(BOOL)barCode qrCode:(BOOL)qrCode document:(BOOL)document;
@optional
/// @method codeScannerView
/// @abstract
/// Called when an image is captured. It provides image with other extracted details
/// @discussion
/// This fuction will be removed in future. Please use codeScannerView (scannerView: CodeScannerView, didCaptureOCRImage image: UIImage, withCroppedImge croppedImage: UIImage?, withBarcodes barcodes: [DetectedCode]) instead.
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didCaptureOCRImage:(UIImage * _Nonnull)image withCroppedImge:(UIImage * _Nullable)croppedImage withbarCodes:(NSArray<NSString *> * _Nonnull)barcodes SWIFT_AVAILABILITY(ios,introduced=15.0,deprecated=17.0);
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didCaptureOCRImage:(UIImage * _Nonnull)image withCroppedImge:(UIImage * _Nullable)croppedImage withBarcodes:(NSArray<DetectedCode *> * _Nonnull)barcodes imageSharpnessScore:(float)imageSharpnessScore;
- (BOOL)codeScannerViewDidCapturePrice:(NSString * _Nonnull)price withSKU:(NSString * _Nonnull)sKU withBoundingBox:(CGRect)boundingBox SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSNumber *> * _Nonnull)codeScannerViewDidCaptureItemCodesWith:(NSArray<DetectedCode *> * _Nonnull)codes SWIFT_WARN_UNUSED_RESULT;
- (void)codeScannerViewdidUpdateSceneWithSharpness:(float)imageSharpnessScore onCameraLiveGuidance:(enum CameraLiveGuidance)onCameraLiveGuidance;
/// RN camera-controls Phase 3 bridge: fires on EVERY <code>VSDKCameraState</code> transition (not just
/// <code>.error</code>, unlike the existing <code>didFailure</code> mapping below) – facing/activeLens/zoom/
/// min/max/torch/focusMode/isPreviewActive, full snapshot. Lets consumers (the RN
/// <code>onCameraStateChanged</code> event) observe state without reaching into <code>cameraSession</code>, which
/// stays private/internal to this view.
- (void)codeScannerView:(CodeScannerView * _Nonnull)scannerView didChangeCameraState:(VSDKCameraState * _Nonnull)state;
@end

SWIFT_CLASS_NAMED("DCReportModel")
@interface DCReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("DetectedCode")
@interface DetectedCode : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stringValue;
@property (nonatomic, readonly) enum BarcodeSymbology symbology;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable extractedData;
@property (nonatomic, readonly) CGRect boundingBox;
/// Bounding box normalized to 0-1 range with top-left origin.
/// Use this when you need device/resolution-independent coordinates.
@property (nonatomic, readonly) CGRect normalizedBoundingBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("DownloadedModelData")
@interface DownloadedModelData : NSObject
@property (nonatomic, copy) NSString * _Nullable modelClass;
@property (nonatomic, copy) NSString * _Nullable modelSize;
@property (nonatomic, copy) NSString * _Nullable modelVersionId;
@property (nonatomic, copy) NSString * _Nullable modelVersion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSBundle;
SWIFT_CLASS_NAMED("GenerateTemplateController")
@interface GenerateTemplateController : UIViewController
+ (GenerateTemplateController * _Nonnull)instantiate SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface GenerateTemplateController (SWIFT_EXTENSION(VisionSDK)) <AVCaptureVideoDataOutputSampleBufferDelegate>
/// Kept per Resolved ambiguity #4 (I5a) – dead-in-practice post-swap, since nothing sets
/// <code>self</code> as any AVCaptureVideoDataOutput’s sample buffer delegate anymore
/// (VSDKCameraSession’s own FrameDispatcher owns that role now). Refactored to funnel
/// through the same onFrame(_:) every real frame now goes through, rather than duplicating
/// its dispatch logic – identical treatment to CodeScannerView’s own equivalent method.
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@interface GenerateTemplateController (SWIFT_EXTENSION(VisionSDK))
- (void)startRunning;
/// Non-blocking by design, exactly like CodeScannerView’s post-migration stopRunning() –
/// cameraSession.stop() hops onto its own session queue and returns immediately.
- (void)stopRunning;
@end

SWIFT_PROTOCOL_NAMED("GenerateTemplateControllerDelegate")
@protocol GenerateTemplateControllerDelegate
- (void)templateScanController:(GenerateTemplateController * _Nonnull)controller didFinishWith:(NSData * _Nonnull)templateData;
- (void)templateScanController:(GenerateTemplateController * _Nonnull)controller didFailWithError:(NSError * _Nonnull)error;
- (void)templateScanControllerDidCancel:(GenerateTemplateController * _Nonnull)controller;
@end

SWIFT_CLASS_NAMED("ILReportModel")
@interface ILReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, OCRMode, open) {
  OCRModeOnline = 0,
  OCRModeOffline = 1,
};

@class ShippingLabelOptions;
@class NSURL;
SWIFT_ENUM_FWD_DECL(NSInteger, VSDKModelExternalClass)
SWIFT_ENUM_FWD_DECL(NSInteger, VSDKModelExternalSize)
@class CIImage;
SWIFT_CLASS_NAMED("OnDeviceOCRManager")
@interface OnDeviceOCRManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OnDeviceOCRManager * _Nonnull shared;)
+ (OnDeviceOCRManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Opt-in cloud address-parsing refinement for shipping-label OCR results. Both flags
/// default <code>false</code> – see <code>ShippingLabelOptions</code>. Consumers set this directly on the
/// singleton (not a per-call parameter) so <code>extractDataFromImageUsing</code>‘s existing @objc
/// selector doesn’t change.
@property (nonatomic, strong) ShippingLabelOptions * _Nonnull shippingLabelOptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSURL * _Nullable)getVSDKLogs SWIFT_WARN_UNUSED_RESULT;
- (void)reportErrorWith:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize image:(CIImage * _Nullable)image reportText:(NSString * _Nonnull)reportText response:(NSData * _Nullable)response reportModel:(VSDKAnalyticsReportModel * _Nullable)reportModel withCompletion:(void (^ _Nullable)(NSInteger))completion;
- (void)downloadModelWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withProgressTracking:(void (^ _Nullable)(float, float))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)cancelDownload:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)loadModelWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)unloadModel:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize;
- (void)deleteModel:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize;
- (float)getImageSharpnessScore:(CIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
- (void)extractDataFromImageUsing:(CIImage * _Nonnull)image withBarcodes:(NSArray<DetectedCode *> * _Nonnull)barcodes checkImageSharpness:(BOOL)checkImageSharpness modelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end

@interface OnDeviceOCRManager (SWIFT_EXTENSION(VisionSDK))
- (void)prepareOfflineOCRWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withProgressTracking:(void (^ _Nullable)(float, float, BOOL))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)extractDataFromImageUsing:(CIImage * _Nonnull)image withBarcodes:(NSArray<DetectedCode *> * _Nonnull)barcodes checkImageSharpness:(BOOL)checkImageSharpness :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end

@interface OnDeviceOCRManager (SWIFT_EXTENSION(VisionSDK))
- (void)checkModelUpdateWithApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token forModelClass:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize withProgressTracking:(void (^ _Nullable)(float, float))progress withCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (BOOL)isModelLoaded:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSDictionary<NSString *, NSString *> *> * _Nonnull)getLoadedModels SWIFT_WARN_UNUSED_RESULT;
- (DownloadedModelData * _Nullable)getDownloadedModel:(enum VSDKModelExternalClass)modelClass withModelSize:(enum VSDKModelExternalSize)modelSize SWIFT_WARN_UNUSED_RESULT;
- (NSArray<DownloadedModelData *> * _Nonnull)getDownloadedModels SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS_NAMED("SLReportModel")
@interface SLReportModel : VSDKAnalyticsReportModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("ShippingLabelOptions")
@interface ShippingLabelOptions : NSObject
@property (nonatomic) BOOL parseRecipientAddress;
@property (nonatomic) BOOL parseSenderAddress;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) ShippingLabelOptions * _Nonnull default_;)
+ (ShippingLabelOptions * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithParseRecipientAddress:(BOOL)parseRecipientAddress parseSenderAddress:(BOOL)parseSenderAddress OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VSDKAppEnvironment, open) {
  VSDKAppEnvironmentDev = 0,
  VSDKAppEnvironmentQa = 1,
  VSDKAppEnvironmentStaging = 2,
  VSDKAppEnvironmentProduction = 3,
  VSDKAppEnvironmentSandbox = 4,
};

SWIFT_ENUM_FWD_DECL(NSInteger, VSDKLensFacing)
@class VSDKLens;
@class NSNumber;
SWIFT_CLASS("_TtC9VisionSDK22VSDKCameraCapabilities")
@interface VSDKCameraCapabilities : NSObject
+ (VSDKCameraCapabilities * _Nonnull)snapshot SWIFT_WARN_UNUSED_RESULT;
- (NSArray<VSDKLens *> * _Nonnull)lensesFor:(enum VSDKLensFacing)facing SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSNumber *> * _Nonnull)zoomStopsFor:(enum VSDKLensFacing)facing SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasTorchFor:(enum VSDKLensFacing)facing SWIFT_WARN_UNUSED_RESULT;
- (BOOL)supportsFocusPointFor:(enum VSDKLensFacing)facing SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, VSDKRotationLock)
SWIFT_CLASS("_TtC9VisionSDK23VSDKCameraConfiguration")
@interface VSDKCameraConfiguration : NSObject
@property (nonatomic, readonly) enum VSDKLensFacing facing;
@property (nonatomic, readonly, strong) VSDKLensSelection * _Nonnull lens;
@property (nonatomic, readonly) enum VSDKRotationLock rotationLock;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("Builder")
@interface VSDKCameraConfigurationBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (VSDKCameraConfigurationBuilder * _Nonnull)facing:(enum VSDKLensFacing)facing;
- (VSDKCameraConfigurationBuilder * _Nonnull)lens:(VSDKLensSelection * _Nonnull)selection;
- (VSDKCameraConfigurationBuilder * _Nonnull)rotationLock:(enum VSDKRotationLock)lock;
- (VSDKCameraConfiguration * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC9VisionSDK20VSDKCameraController")
@interface VSDKCameraController : NSObject
- (void)setZoom:(float)ratio;
- (void)setLinearZoom:(float)linear;
- (float)currentLinearZoom SWIFT_WARN_UNUSED_RESULT;
- (void)setTorchEnabled:(BOOL)enabled;
- (void)setFocusPoint:(CGPoint)point;
- (void)setFocusMode:(enum VSDKFocusMode)mode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VSDKCameraErrorCode, open) {
  VSDKCameraErrorCodePermissionDenied = 0,
  VSDKCameraErrorCodeLensUnavailable = 1,
  VSDKCameraErrorCodeConfigurationFailed = 2,
};

@class VSDKCameraSession;
SWIFT_CLASS("_TtC9VisionSDK21VSDKCameraPreviewView")
@interface VSDKCameraPreviewView : UIView
- (nonnull instancetype)initWithSession:(VSDKCameraSession * _Nonnull)session OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class AVCaptureVideoPreviewLayer;
@protocol VSDKCameraStateObserver;
SWIFT_CLASS("_TtC9VisionSDK17VSDKCameraSession")
@interface VSDKCameraSession : NSObject
@property (nonatomic, readonly, strong) VSDKCameraController * _Nonnull controller;
@property (nonatomic, readonly, strong) VSDKCameraState * _Nonnull currentState;
@property (nonatomic, readonly, strong) AVCaptureVideoPreviewLayer * _Nonnull previewLayer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)addObserver:(id <VSDKCameraStateObserver> _Nonnull)observer;
- (void)removeObserver:(id <VSDKCameraStateObserver> _Nonnull)observer;
- (void)start;
- (void)startWith:(VSDKCameraConfiguration * _Nonnull)configuration;
- (void)updateWith:(VSDKCameraConfiguration * _Nonnull)configuration;
- (void)stop;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, VSDKCameraStatus)
SWIFT_CLASS("_TtC9VisionSDK15VSDKCameraState")
@interface VSDKCameraState : NSObject
@property (nonatomic, readonly) enum VSDKCameraStatus status;
@property (nonatomic, readonly, strong) NSError * _Nullable error;
@property (nonatomic, readonly, strong) NSError * _Nullable warning;
@property (nonatomic, readonly) enum VSDKLensFacing facing;
@property (nonatomic, readonly, strong) VSDKLens * _Nullable activeLens;
@property (nonatomic, readonly) float zoomRatio;
@property (nonatomic, readonly) float minZoomRatio;
@property (nonatomic, readonly) float maxZoomRatio;
@property (nonatomic, readonly) BOOL isTorchEnabled;
@property (nonatomic, readonly) enum VSDKFocusMode focusMode;
/// First-frame-landed lifecycle signal (additive, cross-platform parity with Android’s
/// <code>CameraState.isPreviewActive</code>): <code>true</code> once the CURRENTLY-bound camera has delivered at
/// least one frame to the frame pipeline; <code>false</code> initially, while <code>.idle</code>/<code>.starting</code>, and
/// reset to <code>false</code> on every (re)bind/stop/interrupt/error. See SessionReconciler for the
/// only place this ever flips true.
@property (nonatomic, readonly) BOOL isPreviewActive;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP9VisionSDK23VSDKCameraStateObserver_")
@protocol VSDKCameraStateObserver
- (void)cameraSession:(VSDKCameraSession * _Nonnull)session didChange:(VSDKCameraState * _Nonnull)state;
@end

typedef SWIFT_ENUM(NSInteger, VSDKCameraStatus, open) {
  VSDKCameraStatusIdle = 0,
  VSDKCameraStatusStarting = 1,
  VSDKCameraStatusRunning = 2,
  VSDKCameraStatusInterrupted = 3,
  VSDKCameraStatusError = 4,
};

SWIFT_CLASS_NAMED("VSDKConstants")
@interface Constants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VSDKFocusMode, open) {
  VSDKFocusModeContinuous = 0,
  VSDKFocusModeSingle = 1,
  VSDKFocusModeLocked = 2,
};

SWIFT_ENUM_FWD_DECL(NSInteger, VSDKLensKind)
SWIFT_CLASS("_TtC9VisionSDK8VSDKLens")
@interface VSDKLens : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) enum VSDKLensKind kind;
@property (nonatomic, readonly) enum VSDKLensFacing facing;
@property (nonatomic, readonly) float minZoomRatio;
@property (nonatomic, readonly) float maxZoomRatio;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull zoomSwitchPoints;
@property (nonatomic, readonly) BOOL hasFlash;
@property (nonatomic, readonly) BOOL isLogical;
@property (nonatomic, readonly) BOOL isPinnable;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VSDKLensFacing, open) {
  VSDKLensFacingBack = 0,
  VSDKLensFacingFront = 1,
};

typedef SWIFT_ENUM(NSInteger, VSDKLensKind, open) {
  VSDKLensKindUltraWide = 0,
  VSDKLensKindWide = 1,
  VSDKLensKindTelephoto = 2,
  VSDKLensKindUnknown = 3,
};

SWIFT_CLASS("_TtC9VisionSDK17VSDKLensSelection")
@interface VSDKLensSelection : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VSDKLensSelection * _Nonnull automatic;)
+ (VSDKLensSelection * _Nonnull)automatic SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, VSDKModelExternalClass, open) {
  VSDKModelExternalClassShippingLabel = 0,
  VSDKModelExternalClassBillOfLading = 1,
  VSDKModelExternalClassItemLabel = 2,
  VSDKModelExternalClassDocumentClassification = 3,
};

typedef SWIFT_ENUM(NSInteger, VSDKModelExternalSize, open) {
  VSDKModelExternalSizeNano = 0,
  VSDKModelExternalSizeMicro = 1,
  VSDKModelExternalSizeSmall = 2,
  VSDKModelExternalSizeMedium = 3,
  VSDKModelExternalSizeLarge = 4,
  VSDKModelExternalSizeXlarge = 5,
};

typedef SWIFT_ENUM(NSInteger, VSDKPlatformType, open) {
  VSDKPlatformTypeNative = 0,
  VSDKPlatformTypeFlutter = 1,
  VSDKPlatformTypeReactNative = 2,
};

typedef SWIFT_ENUM(NSInteger, VSDKRotationLock, open) {
  VSDKRotationLockFollowDisplay = 0,
  VSDKRotationLockLockedPortrait = 1,
  VSDKRotationLockLockedLandscape = 2,
};

SWIFT_CLASS_NAMED("VisionAPIManager")
@interface VisionAPIManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VisionAPIManager * _Nonnull shared;)
+ (VisionAPIManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface VisionAPIManager (SWIFT_EXTENSION(VisionSDK))
- (void)checkScanningFeatureAuthenticationWithKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)callScanAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData andRecipient:(NSDictionary<NSString *, id> * _Nullable)recipient andSender:(NSDictionary<NSString *, id> * _Nullable)sender withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)getPredictionBillOfLadingCloud:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callDocumentClassificationAPIWith:(UIImage * _Nonnull)image andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callItemLabelsAPIWith:(UIImage * _Nonnull)image andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callMatchingAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withResponseData:(NSData * _Nonnull)responseData andLocationId:(NSString * _Nullable)locationId andOptions:(NSDictionary<NSString *, id> * _Nonnull)options andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData andRecipient:(NSDictionary<NSString *, id> * _Nullable)recipient andSender:(NSDictionary<NSString *, id> * _Nullable)sender withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callItemLabelsMatchingAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withResponseData:(NSData * _Nonnull)responseData withImageResizing:(BOOL)shouldResizeImage andMetaData:(NSDictionary<NSString *, id> * _Nonnull)metaData :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
- (void)callVLMCloudAPIWith:(UIImage * _Nonnull)image andBarcodes:(NSArray<NSString *> * _Nonnull)barcodes andApiKey:(NSString * _Nullable)apiKey andToken:(NSString * _Nullable)token withImageResizing:(BOOL)shouldResizeImage :(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))completion;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
